### ISSUE TITLE
0.4.0 - undefined method `to_set'

### ISSUE THREAD

**Issue by tmornini** [ruby-grape/grape-entity#54]
After a bundle update I now see this:

```
/home/travis/build/subledger/subledger/vendor/bundle/ruby/2.1.0/gems/grape-entity-0.4.0/lib/grape_entity/entity.rb:485:in `<class:Entity>': undefined method `to_set' for #<Array:0x000000027efa98> (NoMethodError)
  from /home/travis/build/subledger/subledger/vendor/bundle/ruby/2.1.0/gems/grape-entity-0.4.0/lib/grape_entity/entity.rb:43:in `<module:Grape>'
  from /home/travis/build/subledger/subledger/vendor/bundle/ruby/2.1.0/gems/grape-entity-0.4.0/lib/grape_entity/entity.rb:3:in `<top (required)>'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/build/subledger/subledger/vendor/bundle/ruby/2.1.0/gems/grape-entity-0.4.0/lib/grape_entity.rb:3:in `<top (required)>'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/build/subledger/subledger/vendor/bundle/ruby/2.1.0/gems/grape-entity-0.4.0/lib/grape-entity.rb:1:in `<top (required)>'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
  from /home/travis/build/subledger/subledger/lib/subledger/domain.rb:2:in `<top (required)>'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/build/subledger/subledger/lib/subledger.rb:17:in `<top (required)>'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /home/travis/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Same code works fine with 0.3.0

Ideas?

**Comment by shaktiprakash099** [comment]
I am trying to create a cocoapod library on mac after pod lib create iostransition 
i was asked to provide few details  then i got this : undefined method `to_set' for #<Array:0x00007fc0dd179468> (NoMethodError)
Did you mean?  to_s
